pub(crate) mod client;
/// [TRANSPORT] High-performance transport layer module
///
/// Provides unified transport abstraction with support for multiple protocols,
/// lock-free data structures, and intelligent runtime optimization.
///
/// ## Architecture Overview
/// - **Backend Performance**: Lock-free connection pools and optimized memory management
/// - **Frontend Compatibility**: Unified API with backward compatibility
/// - **Progressive Enhancement**: Smart components ready for seamless integration
///
/// ## High-Performance Component Architecture
/// ```text
/// ┌─────────────────────────────────────────────────────────────┐
/// │                   High-Performance Transport                │
/// ├─────────────────┬───────────────────┬───────────────────────┤
/// │   Frontend API   │    Core Processing │    Backend Storage    │
/// ├─────────────────┼───────────────────┼───────────────────────┤
/// │ Transport API    │ Generic Actor     │ LockFree Pools        │
/// │ Unified Interface│ Legacy Compatible │ Optimized Memory      │
/// │ Zero Config      │ Ready for Upgrade │ Detailed Monitoring   │
/// └─────────────────┴───────────────────┴───────────────────────┘
/// ```
///
/// ## User Experience
/// - **Zero Configuration**: `TransportClientBuilder::new().build()` and
///   `TransportServerBuilder::new().build()` automatically enable optimizations
/// - **Full Backward Compatibility**: Existing code works without modification
/// - **Transparent Performance**: Memory allocation and connection management
///   automatically use high-performance implementations
pub(crate) mod config;
pub(crate) mod connection_state;
pub(crate) mod limits;
pub(crate) mod request_registry;
pub(crate) mod server;
pub(crate) mod transport;
pub(crate) mod transport_server;

pub(crate) mod context;
pub(crate) mod lockfree;
// The read-buffer pool is a byte-stream (TCP/QUIC) optimization; WebSocket
// framing does its own buffering, so the pool is gated to those protocols.
#[cfg(any(feature = "tcp", feature = "quic"))]
pub(crate) mod memory_pool;
pub(crate) mod session_actor;

// [EXPORTS] Re-export core APIs with unified architecture
pub use client::{RetryConfig, TransportClient, TransportClientBuilder};
pub use server::TransportServerBuilder;
pub use transport_server::{ShutdownReport, TransportServer};
// Extension SPI (used by custom protocol adapters) reachable via the crate root.

// [CONFIG] Configuration exports
pub use config::TransportConfig;

// Internal performance machinery (memory pool, lock-free primitives) is not
// part of the public API; the modules stay crate-internal.

// [CONNECTION] Lock-free connection exports

// [STATE] Connection state management exports
// Request lifecycle state machine is internal (crate::transport::request_registry).

use crate::packet::CompressionType;
use bytes::Bytes;
use std::time::Duration;

/// Transport options for customizing send/request behavior
#[derive(Default, Clone, Debug)]
pub struct TransportOptions {
    /// Timeout duration (only effective for requests)
    pub(crate) timeout: Option<Duration>,
    /// Compression algorithm
    pub(crate) compression: Option<CompressionType>,
    /// Application-layer business type ID
    pub(crate) biz_type: Option<u8>,
    /// Extended header content (business layer encoded)
    pub(crate) ext_header: Option<Bytes>,
    /// Message ID (optional, auto-generated by default)
    pub(crate) message_id: Option<u32>,
}

impl TransportOptions {
    /// Create new transport options
    pub fn new() -> Self {
        Self::default()
    }

    /// Set timeout duration
    pub fn timeout(mut self, timeout: Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Set compression algorithm
    pub fn compression(mut self, compression: CompressionType) -> Self {
        self.compression = Some(compression);
        self
    }

    /// Set business type
    pub fn biz_type(mut self, biz_type: u8) -> Self {
        self.biz_type = Some(biz_type);
        self
    }

    /// Set extended header
    pub fn ext_header(mut self, ext_header: Bytes) -> Self {
        self.ext_header = Some(ext_header);
        self
    }

    /// Set message ID
    pub fn message_id(mut self, message_id: u32) -> Self {
        self.message_id = Some(message_id);
        self
    }
}

// [ACTOR] Session actor model exports
// Public handler API: Responder / SessionHandler / SessionSender.
pub use session_actor::{Responder, SessionHandler, SessionSender};
// Actor internals stay crate-private (crate::transport::session_actor).
